apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  generation: 1
  name: no-proxysql-ssl-internal
  ownerReferences:
  - apiVersion: pxc.percona.com/v1
    controller: true
    kind: PerconaXtraDBCluster
    name: no-proxysql
spec:
  commonName: no-proxysql-pxc
  dnsNames:
  - '*.no-proxysql-pxc'
  isCA: true
  issuerRef:
    kind: Issuer
    name: no-proxysql-pxc-ca
  secretName: no-proxysql-ssl-internal
