apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  generation: 1
  name: some-name-haproxy
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: StatefulSet
    name: some-name-haproxy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: haproxy
      app.kubernetes.io/instance: some-name
      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
